### ISSUE TITLE
Electron source build

### ISSUE THREAD

**Issue by faveoled** [flathub/org.pgadmin.pgadmin4#5]
I attempted to generate npm sources using the latest yarn.lock and got this error:
```
$ flatpak-node-generator yarn yarn.lock 
Reading packages from lockfiles...
Traceback (most recent call last):
  File "/home/user/.local/bin/flatpak-node-generator", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.local/share/pipx/venvs/flatpak-node-generator/lib/python3.12/site-packages/flatpak_node_generator/main.py", line 277, in main
    asyncio.run(_async_main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/flatpak-node-generator/lib/python3.12/site-packages/flatpak_node_generator/main.py", line 198, in _async_main
    packages.update(lockfile_provider.process_lockfile(lockfile))
  File "/home/user/.local/share/pipx/venvs/flatpak-node-generator/lib/python3.12/site-packages/flatpak_node_generator/providers/yarn.py", line 106, in process_lockfile
    for name_line, package in self.parse_lockfile(lockfile).items():
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/flatpak-node-generator/lib/python3.12/site-packages/flatpak_node_generator/providers/yarn.py", line 68, in parse_lockfile
    key, value = shlex.split(line)
    ^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
```
Looks like this issue would depend on completion of:
https://github.com/flatpak/flatpak-builder-tools/issues/361

**Comment by nazebzurati** [comment]
Should this be closed? As mentioned in [https://github.com/flatpak/flatpak-builder-tools/issues/361](https://github.com/flatpak/flatpak-builder-tools/issues/361), only v1 lockfiles are supported.

**Comment by faveoled** [comment]
But we still don't have source build..
